# Generated by Django 4.0.5 on 2022-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None, unique=True)),
                ('code', models.TextField(default=None, unique=True)),
                ('hint_html', models.TextField(default=None, unique=True)),
            ],
        ),
    ]
