# Generated by Django 4.0.5 on 2022-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.TextField(default=None, unique=True)),
                ('members', models.TextField(default=None, unique=True)),
                ('progress', models.IntegerField(default=None)),
            ],
        ),
    ]
