# Generated by Django 4.0.5 on 2022-06-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.DateTimeField(blank=True, default=None, null=True)),
                ('two', models.DateTimeField(blank=True, default=None, null=True)),
                ('three', models.DateTimeField(blank=True, default=None, null=True)),
                ('four', models.DateTimeField(blank=True, default=None, null=True)),
                ('five', models.DateTimeField(blank=True, default=None, null=True)),
                ('six', models.DateTimeField(blank=True, default=None, null=True)),
                ('seven', models.DateTimeField(blank=True, default=None, null=True)),
                ('eight', models.DateTimeField(blank=True, default=None, null=True)),
                ('nine', models.DateTimeField(blank=True, default=None, null=True)),
                ('ten', models.DateTimeField(blank=True, default=None, null=True)),
                ('eleven', models.DateTimeField(blank=True, default=None, null=True)),
                ('twelve', models.DateTimeField(blank=True, default=None, null=True)),
                ('twelve2', models.DateTimeField(blank=True, default=None, null=True)),
                ('team', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
    ]
